version: '3.4'

services:
  catalogdb:
    image : mongo

  productapi:
    image: ${DOCKER_REGISTRY-}productapi
    build:
      context: .
      dockerfile: ProductAPI/Dockerfile

volumes:
  mongo_data:   


#Docker-Compose comandos :

#	docker-compose -f docker-compose.yml -f docker-compose.override.yml up --build
#	ou
#	docker-compose -f docker-compose.yml -f docker-compose.override.yml up -d
#	docker-compose -f docker-compose.yml -f docker-compose.override.yml down